server:
  port: 80
ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
#  OkToRetryOnAllOperations: true # 是否对所有操作重试
#  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
#  MaxAutoRetries: 1 # 同一实例的重试次数
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000 # 熔断超时时长：6000ms++++++++
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
zuul:
  #清空敏感头配置
  sensitiveHeaders:
  routes:
    default:
      path: /**
      serviceId: shop-index
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 60000
#    retryable: true