server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka

ds1:
  datasource:
    url: jdbc:mysql://localhost:3306/db_onlineshopping?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 232328
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 20
    minIdle: 20
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20