server:
  port: 8400
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
spring:
  datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot
  username: root
  password: 1234
  type: com.mchange.v2.c3p0.ComboPooledDataSource