server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/db_onlineshopping?serverTimezone=GMT%2B8
#    username: root
#    password: 232328
#    hikari:
#      max-lifetime: 1765000
#      maximumPoolSize: 15