spring:
  application:
    name: shop-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Computer-service-platform/-Computer-service-platform
          default-label: master
          search-paths: shop-pc/config

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
